.include "macros.inc"

;*******************************************************************************
; ENABLE
; Reenables NMI's by acking the one that was held in an unacknowledged state
.export __nmi_enable
.proc __nmi_enable
	IO_BEGIN
	bit $dd0d	; ACK NMI
	IO_DONE
	rts
.endproc

;*******************************************************************************
; DISABLE
; Disables NMI's from being generated by generating and not ack'ing an NMI
.export __nmi_disable
.proc __nmi_disable
	IO_BEGIN
        lda #<@nmi
        sta $0318
        lda #>@nmi
        sta $0319
        lda #$00
        sta $dd0e
        sta $dd04
        sta $dd05
        lda #$81
        sta $dd0d
        lda #$01
        sta $dd0e
	IO_DONE
	rts

@nmi:	rti
.endproc
